package com.my.dbsearchquery.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.my.dbsearchquery.bean.CaseInfo;

import com.my.dbsearchquery.dao.CaseInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig caseInfoDaoConfig;

    private final CaseInfoDao caseInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        caseInfoDaoConfig = daoConfigMap.get(CaseInfoDao.class).clone();
        caseInfoDaoConfig.initIdentityScope(type);

        caseInfoDao = new CaseInfoDao(caseInfoDaoConfig, this);

        registerDao(CaseInfo.class, caseInfoDao);
    }
    
    public void clear() {
        caseInfoDaoConfig.getIdentityScope().clear();
    }

    public CaseInfoDao getCaseInfoDao() {
        return caseInfoDao;
    }

}
